[Improvement] Add set of bugfixes from the EE
Signed-off-by: Alvaro Cano <alvaro.cano@zevenet.com>

diff --git a/usr/local/zevenet/bin/nftlbd b/usr/local/zevenet/bin/nftlbd
--- a/usr/local/zevenet/bin/nftlbd
+++ b/usr/local/zevenet/bin/nftlbd
@@ -1,11 +1,22 @@
-#!/bin/sh
+#!/bin/bash
 
 DEBUG=""
 GLOBALCONF="/usr/local/zevenet/config/global.conf"
+
+if [ -f "/usr/local/zevenet/bin/load_global_conf" ];
+then
+	source /usr/local/zevenet/bin/load_global_conf
+	load_global_conf
+else
+	echo "Error loading the envirovement"
+	exit
+fi
+NFTBIN=$nft_bin
+
 if [ -f "$GLOBALCONF" ]; then
-	LEVEL=`grep ^.debug= "$GLOBALCONF" | awk -F'"' '{ printf $2 }' 2> /dev/null`
-	if [ ! -z $LEVEL ] && [ "$LEVEL" != "0" ]; then
-		DEBUG="-l $LEVEL"
+	# debug
+	if [ ! -z $debug ] && [ "$debug" != "0" ]; then
+		DEBUG="-l $debug"
 	fi
 fi
 
@@ -13,7 +24,6 @@ DESC="nftlb daemon service"
 NAME=nftlb
 DAEMON=/usr/local/zevenet/app/nftlb/sbin/nftlb
 DAEMON_ARGS="$DEBUG -H 127.0.0.1 -k HoLa -P 27"
-NFTBIN=`which nft`
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
@@ -25,14 +35,16 @@ SCRIPTNAME=/etc/init.d/$NAME
 do_start()
 {
 	start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS
-	[ "$?" -ne 0 ] && return 2
+	[ "$?" -ne 0 ] && exit 2
 }
 
 do_stop() {
-	`$NFTBIN flush ruleset`
 	start-stop-daemon --stop --signal 1 --quiet --remove-pidfile --pidfile $PIDFILE --name $NAME
+	PID=`pidof nftlb`
+	[ -n "$PID" ] && kill -9 $PID
+	`$NFTBIN delete table ip nftlb 2> /dev/null`
+	`$NFTBIN delete table netdev nftlb 2> /dev/null`
 	[ -f $PIDFILE ] && rm -i $PIDFILE
-	[ "$?" -ne 0 ] && return 2
 }
 
 case "$1" in
@@ -40,8 +52,8 @@ case "$1" in
 		echo "Starting $DESC" "$NAME"
 		do_start
 		case "$?" in
-		0|1) return 0 ;;
-		2) return 1 ;;
+		0|1) exit 0 ;;
+		2) exit 1 ;;
 		esac
 		;;
 
@@ -49,8 +61,8 @@ case "$1" in
 		echo "Stopping $DESC" "$NAME"
 		do_stop
 		case "$?" in
-		0|1) return 0 ;;
-		2) return 1 ;;
+		0|1) exit 0 ;;
+		2) exit 1 ;;
 		esac
 		;;
 
@@ -65,13 +77,13 @@ case "$1" in
 		0|1)
 			do_start
 			case "$?" in
-				0) return 0 ;;
-				1) return 1 ;;
-				*) return 1 ;;
+				0) exit 0 ;;
+				1) exit 1 ;;
+				*) exit 1 ;;
 			esac
 			;;
 		*)
-			return 1	;;
+			exit 1	;;
 		esac
 		;;
 
